### ISSUE TITLE
Include file using lems.api

### ISSUE THREAD

**Issue by dokato** [LEMS/pylems#26]
Hello,

I would like to ask if there is any possibility to include an external file to my own XML using lems.api model? I mean a line like this:

```
<Include file="NeuroMLCoreDimensions.xml" />
```

I tried to use `model.include_file` but it adds all tags from specified file instead of just its name.

**Comment by pgleeson** [comment]
Hi @dokato, sorry for the delay in responding. I started a reply justifying why it wasn't there and offering alternatives, but then I just went and added it. See https://github.com/LEMS/pylems/commit/ea00df59c4442fad5cc7ce4558d8f94da77d7878. Hope this serves your purposes.

**Comment by dokato** [comment]
Perfect :+1: Thank you!
