### ISSUE TITLE
lems assign

### ISSUE THREAD

**Issue by dokato** [LEMS/pylems#30]
Hi, following an example https://github.com/LEMS/jLEMS/blob/development/src/test/resources/ex-properties.xml I tried to reproduce something similar using pylems, especially that part:

```
<Structure>
    <MultiInstantiate componentType="spikeGenerator" number="n">
          <Assign property="period" 
                  value="minPeriod + (maxPeriod - minPeriod) * index/n"/>
    </MultiInstantiate>
</Structure>
```

but I don't see `lems.Assign` class. Is there any other way to add assignments to MultiInstantiate ?

**Comment by pgleeson** [comment]
@dokato sorry for silence on these issues, I had been travelling all last week. I'll get round to them all in the next few days.

**Comment by pgleeson** [comment]
Fixed with https://github.com/LEMS/pylems/pull/32
