### ISSUE TITLE
[feature] exporting dom

### ISSUE THREAD

**Issue by dokato** [LEMS/pylems#33]
I have another suggestion, which could be really helpful when working with pylems.  I noticed that in some cases I need to join LEMS and NeuroML functionality or sometimes add some external XML tags. So I would be great to have an opportunity to export final model not only to XML file but also as a DOM structure.

It shouldn't be a big deal as in `Model.export_to_file` parsing to DOM is already done.

**Comment by pgleeson** [comment]
Merged.
