### ISSUE TITLE
Packaging license file

### ISSUE THREAD

**Issue by jakirkham** [LEMS/pylems#39]
Please add `LICENSE.lesser` to the `MANIFEST.in` file.

**Comment by sanjayankur31** [comment]
Please include the license file. Most downstream distributions require the license to be shipped with the softawre they carry.

**Comment by jakirkham** [comment]
Fixed in commit ( https://github.com/LEMS/pylems/commit/f56b415052d6da679bcdf1247e19b245a9d8a0a8 ). Should show up in the next release. So will go ahead and close.
