### ISSUE TITLE
Examples are not included in the pypi package

### ISSUE THREAD

**Issue by sanjayankur31** [LEMS/pylems#42]
The documentation mentions the examples, but these aren't included in the pypi install. Please include them.

**Comment by pgleeson** [comment]
These are mentioned in the https://github.com/LEMS/pylems/blob/master/MANIFEST.in file... Is there something else in setup.py that needs to be added to propagate these additions?

**Comment by mstimberg** [comment]
The `MANIFEST.in` file uses `include examples *.xml`, this should be `include examples/*.xml` (or simply `include examples/*` given that there are also `.py` files.

**Comment by pgleeson** [comment]
The examples, along with the licence file, are now included in the release file at https://pypi.org/project/PyLEMS/0.4.9.3/#files.
