### ISSUE TITLE
Conversion to NEURON

### ISSUE THREAD

**Issue by rgerkin** [LEMS/pylems#44]
Is it possible to use pylems to convert NeuroML + LEMS to NEURON for simulation, analogous to a command like `jnml some_model.xml -neuron -run` in jNeuroML?  Will this ever be possible?

**Comment by pgleeson** [comment]
Not with pylems, but with pyneuroml... The main logic of the NML->NEURON converter, developed over years and handling all the edge cases for how best Neuron should handle different channels and cells is in 4000+ lines here: https://github.com/NeuroML/org.neuroml.export/blob/development/src/main/java/org/neuroml/export/neuron/NeuronWriter.java, and is unlikely to be converted to Python any time soon. This functionality is included in pyNeuroML as a bundled Java Jar file, and can be accessed with a call to [run_lems_with_jneuroml_neuron(...)](https://github.com/NeuroML/pyNeuroML/blob/c04694e451e208f29eae2f35089f0d07dcb09038/pyneuroml/pynml.py#L567).

Running in NetPyNE goes some of the way to having a pure Python impl of NML->NEURON (as NetPyNE reads the NML itself and converts the cells/networks to its own format), but the channels in NMODL still need to be converted from NML by jnml...

**Comment by rgerkin** [comment]
OK, thanks!
