### ISSUE TITLE
Update and move examples to LEMS

### ISSUE THREAD

**Issue by sanjayankur31** [LEMS/pylems#56]
What do we need to do with the examples here? Copy them over to LEMS?

I wonder if there is a better way of keeping examples in one place and then referring to this from wherever required, otherwise we're duplicating the same files in multiple repositories and will have to ensure we keep them in sync manually.

**Comment by pgleeson** [comment]
I knew you'd pick up on this...
They're also here: https://github.com/LEMS/jLEMS/tree/master/src/test/resources...

If it's simple to update the ci to use and test with the examples from lems (and check in readme etc. for any reference), then it should be a simple fix. JLems might be more work as it uses the examples in generating its docs...

An alternative might just be to pull the latest examples from the lems repo during CI tests and test that they're all identical, throwing an error if there's a difference..
