### ISSUE TITLE
Incorrect Parsing of 'symbol' and 'description' Attributes in LEMS XML `<Constant>` Elements

### ISSUE THREAD

**Issue by leon-k-martin** [LEMS/pylems#77]
## Issue Description:
While working with the LEMS XML parsing functionality, I noticed an issue in the `parse_constant` method of the LEMS file parser in `lems/parser/LEMS.py`. 
Specifically, the `symbol` attribute within `<Constant>` elements is not being correctly parsed. Instead, the `description` attribute from the XML is mistakenly assigned to the `symbol` attribute in the corresponding Python object. This misassignment leads to incorrect representation of the `<Constant>` elements and potential loss of model information.

## Example of Issue:
In the LEMS XML, a `<Constant>` element, like
```xml
<Constant name="A" symbol="A" value="3.25" dimension="lo=2.6, hi=9.75, step=0.05" description="Maximum amplitude of EPSP mV Also called average synaptic gain "/>
```
is parsed as follows:
```python
{'name': 'A', 'symbol': 'Maximum amplitude of EPSP mV Also called average synaptic gain ', 'value': '3.25', 'dimension': 'lo=2.6, hi=9.75, step=0.05', 'description': '', 'numeric_value': None}
```

## Proposed Solution:
I have prepared a fix for this issue, which involves correctly parsing the symbol attribute and ensuring it is accurately passed to the Constant constructor. I'll submit a pull request with this fix for further review and integration.

I am looking forward to any feedback or suggestions regarding this issue.
L

**Comment by pgleeson** [comment]
Fixed by https://github.com/LEMS/pylems/pull/78
